services:
  - type: web
    name: erp-management-system
    env: python
    buildCommand: "gunicorn app:app"
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
